spring:
    profiles:
        active: dev
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
        show-sql: true
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:15432/merit-money-dev
        username: merit_money
        password: merit
    flyway:
        enabled: false #Habilitar e desabilitar auto run do flyway

logging:
    level:
      root: INFO
      org.springframework.web: INFO

usuario:
    disco:
        diretorio-foto: fotos/usuarios
        raiz: ./src/main/resources/static/

email:
    password: mert!mon3y
    sender: meritmoneyruler@gmail.com